### PR TITLE
Install bs58check + Run npm audit fix

### LINKED ISSUE #7: Cannot find module 'bs58check'
The `bs58check` module is being imported here: https://github.com/tacoinfra/tezos-kms/blob/62eda1f34321a0d566ed2105a873cdb7a4c0a70c/src/utils.ts#L13

But the node module is not specified in the package.json.

```shell
  pulumi:pulumi:Stack (tezos-aws-tutorial):
    error: Running program '/Users/aryehharris/Desktop/tezos-pulumi/examples/tutorial' failed with an unhandled exception:
    Error: Cannot find module 'bs58check'
    Require stack:
    - /Users/aryehharris/Desktop/tezos-pulumi/examples/tutorial/node_modules/@tacoinfra/tezos-kms/build/src/utils.js
    - /Users/aryehharris/Desktop/tezos-pulumi/examples/tutorial/node_modules/@tacoinfra/tezos-kms/build/src/tezos-kms-client.js
    - /Users/aryehharris/Desktop/tezos-pulumi/examples/tutorial/node_modules/@tacoinfra/tezos-kms/build/src/index.js
    - /Users/aryehharris/Desktop/tezos-pulumi/examples/tutorial/index.ts
    - /Users/aryehharris/Desktop/tezos-pulumi/examples/tutorial/node_modules/@pulumi/pulumi/cmd/run/run.js
    - /Users/aryehharris/Desktop/tezos-pulumi/examples/tutorial/node_modules/@pulumi/pulumi/cmd/run/index.js
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
        at Function.Module._load (node:internal/modules/cjs/loader:774:27)
        at Module.require (node:internal/modules/cjs/loader:1013:19)
        at require (node:internal/modules/cjs/helpers:93:18)
        at Object.<anonymous> (/Users/aryehharris/Desktop/tezos-pulumi/examples/tutorial/node_modules/@tacoinfra/tezos-kms/src/utils.ts:13:21)
        at Module._compile (node:internal/modules/cjs/loader:1109:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
        at Module.load (node:internal/modules/cjs/loader:989:32)
        at Function.Module._load (node:internal/modules/cjs/loader:829:14)
        at Module.require (node:internal/modules/cjs/loader:1013:19)
```

### PR DESCRIPTION
**Pull request by harryttd**
closes #7 

I also updated packages that fixed vulnerabilites.
```shell
❯ npm audit
# npm audit report

ansi-regex  4.0.0 - 4.1.0 || 5.0.0
Severity: high
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/eslint/node_modules/ansi-regex
node_modules/table/node_modules/ansi-regex

aws-sdk  <2.814.0
Severity: high
Prototype Pollution via file load in aws-sdk and @aws-sdk/shared-ini-file-loader - https://github.com/advisories/GHSA-rrc9-gqf8-8rwg
fix available via `npm audit fix`
node_modules/aws-sdk

elliptic  <6.5.4
Severity: moderate
Use of a Broken or Risky Cryptographic Algorithm - https://github.com/advisories/GHSA-r9p9-mrjm-926w
fix available via `npm audit fix`
node_modules/elliptic

glob-parent  <5.1.2
Severity: moderate
glob-parent before 6.0.1 and 5.1.2 vulnerable to Regular Expression Denial of Service (ReDoS) - https://github.com/advisories/GHSA-cj88-88mr-972w
fix available via `npm audit fix`
node_modules/glob-parent

hosted-git-info  <2.8.9
Severity: moderate
Regular Expression Denial of Service in hosted-git-info - https://github.com/advisories/GHSA-43f8-2h32-f4cj
fix available via `npm audit fix`
node_modules/hosted-git-info

lodash  <=4.17.20
Severity: high
Command Injection in lodash - https://github.com/advisories/GHSA-35jh-r3h4-6jhm
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
fix available via `npm audit fix`
node_modules/lodash

minimist  <1.2.6
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix`
node_modules/minimist

path-parse  <1.0.7
Severity: moderate
Regular Expression Denial of Service in path-parse - https://github.com/advisories/GHSA-hj48-42vr-x3v9
fix available via `npm audit fix`
node_modules/path-parse

8 vulnerabilities (4 moderate, 3 high, 1 critical)

To address all issues, run:
  npm audit fix
```

### CODE REVIEW

**Comment by harryttd** [comment]
@elric1 @keefertaylor Could someone please review this?

**Comment by keefertaylor** [comment]
Taking a look...

**Comment by keefertaylor** [comment]
@harryttd I've cut version 1.1.2 that has this fix in it! Thanks for the contribution!

**Comment by harryttd** [comment]
Thank you!

**Pull request merged**
